Repository pagopa/pagopa-jwt-issuer-service, pull requests merged in 2025-05, with the labels that each got.

#1 [CHK4126] feat(init): init new repo
  .dockerignore
  .gitattributes
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/check-pr-semver-labels/action.yml
  .github/workflows/check_pr.yml
  .gitignore
  .java-version
  .sdkmanrc
  CODEOWNERS
  build.gradle.kts
  eclipse-style.xml
  gradle.properties
  settings.gradle.kts
  src/main/kotlin/it/pagopa/touchpoint/jwtissuerservice/JwtissuerserviceApplication.kt
  src/main/resources/application.properties
  src/main/resources/banner.txt
  src/main/resources/logback-spring.xml
  src/test/kotlin/it/pagopa/touchpoint/jwtissuerservice/JwtissuerserviceApplicationTests.kt
Labels: chart-patch, patch, size/large

#2 [CHK-4126] chore(init): add gradle wrapper
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: chart-patch, patch

#3 Chk 4127 code review pipeline
  .devops/azure-templates/api-tests.yml
  .devops/code-review-pipelines.yml
  .env.example
  Dockerfile.jvm
  Dockerfile.native
  api-tests/jwt_token_issuer_service.postman_collection.json
  docker-compose.yml
Labels: skip-release, size/large

#4 feat: openapi + POST tokens implementation
  .env.example
  Dockerfile.jvm
  Dockerfile.native
  api-spec/v1/openapi.yaml
  api-tests/jwt_token_issuer_service.postman_collection.json
  build.gradle.kts
  src/main/kotlin/it/pagopa/touchpoint/jwtissuerservice/JwtIssuerServiceApplication.kt
  src/main/kotlin/it/pagopa/touchpoint/jwtissuerservice/controllers/TokensController.kt
  src/main/kotlin/it/pagopa/touchpoint/jwtissuerservice/controllers/WellKnownController.kt
  src/main/kotlin/it/pagopa/touchpoint/jwtissuerservice/exceptions/ApiError.kt
  src/main/kotlin/it/pagopa/touchpoint/jwtissuerservice/exceptions/RestApiException.kt
  src/main/kotlin/it/pagopa/touchpoint/jwtissuerservice/exceptions/handlers/ExceptionHandler.kt
  src/main/kotlin/it/pagopa/touchpoint/jwtissuerservice/services/TokensService.kt
  src/main/kotlin/it/pagopa/touchpoint/jwtissuerservice/utils/JwtTokenUtils.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/touchpoint/jwtissuerservice/controllers/TokensControllerTest.kt
  src/test/kotlin/it/pagopa/touchpoint/jwtissuerservice/controllers/WellKnownControllerTest.kt
  src/test/kotlin/it/pagopa/touchpoint/jwtissuerservice/exceptions/handlers/ExceptionHandlerTest.kt
  src/test/kotlin/it/pagopa/touchpoint/jwtissuerservice/services/TokensServiceTest.kt
  src/test/kotlin/it/pagopa/touchpoint/jwtissuerservice/utils/JwtTokenUtilsTest.kt
  src/test/resources/application.test.properties
  src/test/resources/logback-spring.xml
Labels: chart-minor, minor, size/large

#5 [CHK-4128] feat(devops): add cicd pipeline
  .devops/azure-templates/chart-current-version.yml
  .devops/azure-templates/deployment-pipeline.yml
  .devops/azure-templates/helm-microservice-chart-deploy.yml
  .devops/ecommerce-deploy-pipelines.yml
  .devops/pay-wallet-deploy-pipelines.yml
  .github/workflows/deploy.yml
  .github/workflows/semver_release.yaml
  README.md
  helm/.helmignore
  helm/Chart.lock
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  helm/valuesOverrides/ecommerce/overrides-dev.yaml
  helm/valuesOverrides/ecommerce/overrides-prod.yaml
  helm/valuesOverrides/ecommerce/overrides-uat.yaml
  helm/valuesOverrides/overrides-jvm-dev.yaml
  helm/valuesOverrides/overrides-jvm-uat.yaml
  helm/valuesOverrides/pay-wallet/overrides-dev.yaml
  helm/valuesOverrides/pay-wallet/overrides-prod.yaml
  helm/valuesOverrides/pay-wallet/overrides-uat.yaml
Labels: chart-patch, patch, size/large

#6 Chk 4132 integration tests on deployment pipeline
  .devops/azure-templates/api-tests.yml
  .devops/azure-templates/deployment-pipeline.yml
  .devops/code-review-pipelines.yml
  api-tests/ecommerce-dev.env.json
  api-tests/ecommerce-uat.env.json
  api-tests/jwt-token-issuer-service.postman-collection.json
  api-tests/localhost.env.json
  api-tests/pay-wallet-dev.env.json
  api-tests/pay-wallet-uat.env.json
  helm/values-dev.yaml
  src/main/kotlin/it/pagopa/touchpoint/jwtissuerservice/services/TokensService.kt
  src/test/kotlin/it/pagopa/touchpoint/jwtissuerservice/services/TokensServiceTest.kt
Labels: skip-release, size/large

#9 [CHK-4131] feat(apis): POST /tokens and GET /tokens/keys implementation
  .env.example
  README.md
  docker-compose.yml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  helm/valuesOverrides/ecommerce/overrides-dev.yaml
  helm/valuesOverrides/ecommerce/overrides-prod.yaml
  helm/valuesOverrides/ecommerce/overrides-uat.yaml
  helm/valuesOverrides/pay-wallet/overrides-dev.yaml
  helm/valuesOverrides/pay-wallet/overrides-prod.yaml
  helm/valuesOverrides/pay-wallet/overrides-uat.yaml
  src/main/kotlin/it/pagopa/touchpoint/jwtissuerservice/JwtIssuerServiceApplication.kt
  src/main/kotlin/it/pagopa/touchpoint/jwtissuerservice/config/CacheConfig.kt
  src/main/kotlin/it/pagopa/touchpoint/jwtissuerservice/config/properties/CacheConfigProperties.kt
  src/main/kotlin/it/pagopa/touchpoint/jwtissuerservice/models/PrivateKeyWithKid.kt
  src/main/kotlin/it/pagopa/touchpoint/jwtissuerservice/models/PublicKeyWithKid.kt
  src/main/kotlin/it/pagopa/touchpoint/jwtissuerservice/services/IReactiveSecurityKeysService.kt
  src/main/kotlin/it/pagopa/touchpoint/jwtissuerservice/services/ReactiveAzureKVSecurityKeysService.kt
  src/main/kotlin/it/pagopa/touchpoint/jwtissuerservice/services/TokensService.kt
  src/main/kotlin/it/pagopa/touchpoint/jwtissuerservice/utils/JwtTokenUtils.kt
  src/main/resources/META-INF/native-image/reflect-config.json
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/touchpoint/jwtissuerservice/services/ReactiveAzureKVSecurityKeysServiceTest.kt
  src/test/kotlin/it/pagopa/touchpoint/jwtissuerservice/services/TokensServiceTest.kt
  src/test/kotlin/it/pagopa/touchpoint/jwtissuerservice/utils/JwtTokenUtilsTest.kt
  src/test/kotlin/it/pagopa/touchpoint/jwtissuerservice/utils/KeyGenerationTestUtils.kt
  src/test/resources/application.test.properties
Labels: chart-minor, minor, size/small

#11 [CHK-4131] fix(deploy): fix prod approval condition
  .devops/azure-templates/deployment-pipeline.yml
Labels: chart-patch, patch, size/small

#12 [CHK-4131] fix(deploy): fix uat test agent pool
  .devops/azure-templates/deployment-pipeline.yml
Labels: chart-patch, patch, size/small

#13 Revert "fix(deploy): fix uat test agent pool (#12)"
  .devops/azure-templates/deployment-pipeline.yml
Labels: chart-patch, patch, size/small

#14 [CHK-4185] fix(jwt): apply various fix after soak test
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  helm/valuesOverrides/pay-wallet/overrides-dev.yaml
  helm/valuesOverrides/pay-wallet/overrides-prod.yaml
  helm/valuesOverrides/pay-wallet/overrides-uat.yaml
  src/main/kotlin/it/pagopa/touchpoint/jwtissuerservice/services/ReactiveAzureKVSecurityKeysService.kt
  src/test/kotlin/it/pagopa/touchpoint/jwtissuerservice/services/ReactiveAzureKVSecurityKeysServiceTest.kt
Labels: chart-minor, minor, size/small

#15 [CHK-4190] feat(api): add wellknown api implementation
  .env.example
  README.md
  helm/valuesOverrides/ecommerce/overrides-dev.yaml
  helm/valuesOverrides/ecommerce/overrides-prod.yaml
  helm/valuesOverrides/ecommerce/overrides-uat.yaml
  helm/valuesOverrides/pay-wallet/overrides-dev.yaml
  helm/valuesOverrides/pay-wallet/overrides-prod.yaml
  helm/valuesOverrides/pay-wallet/overrides-uat.yaml
  src/main/kotlin/it/pagopa/touchpoint/jwtissuerservice/controllers/WellKnownController.kt
  src/main/kotlin/it/pagopa/touchpoint/jwtissuerservice/services/TokensService.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/touchpoint/jwtissuerservice/controllers/WellKnownControllerTest.kt
  src/test/kotlin/it/pagopa/touchpoint/jwtissuerservice/services/TokensServiceTest.kt
  src/test/resources/application.test.properties
Labels: chart-minor, minor, size/small
